### ISSUE TITLE
DeminifyStackTraceResult should include the error message

### ISSUE THREAD

**Issue by christiango** [microsoft/sourcemap-toolkit#48]
The error.stack object looks like this:
TypeError: Cannot read property 'length' of undefined
    at http://localhost:11323/crashcauser.min.js:1:125
    at i (http://localhost:11323/crashcauser.min.js:1:137)
    at t (http://localhost:11323/crashcauser.min.js:1:75)
    at n (http://localhost:11323/crashcauser.min.js:1:50)
    at causeCrash (http://localhost:11323/crashcauser.min.js:1:341)
    at HTMLButtonElement.<anonymous> (http://localhost:11323/crashcauser.min.js:1:445)

DeminifyStackTraceResult only returns the deminified method names, it would be nice to also return the error message as part of that data structure

**Comment by ian-craig** [comment]
Fixed by #71
